### ISSUE TITLE
Was this controller giving you issues?

### ISSUE THREAD

**Issue by rkmiller131** [ChronosTrade/FEC#28]
Here you are deconstructing the req.body and sending over the exact same object. You could just send over the req.body.

https://github.com/ChronosTrade/FEC/blob/7901c01eddff6b08e696eee858ef74003addf371/server/controllers.js#L69-L93

Also, the parameters are incorrect for productId (should be product_id)
And if you send over the correct body from the front end, all you need for this controller is:

![Screenshot 2023-08-18 at 1 35 23 PM](https://github.com/ChronosTrade/FEC/assets/21061780/6fb99776-d0b7-420d-8135-3bf8b4d01aaa)

**Comment by zulliu** [comment]
Thank you for the review! The correct request handler has been updated.
