### ISSUE TITLE
Just bein nitpicky

### ISSUE THREAD

**Issue by rkmiller131** [ChronosTrade/FEC#35]
I know there are already so many files, but this component could be in its own file.

I do love the way you used indexes for your image selection, it's been very readable and easy to follow your logic.
That said there is a slight bug: When you scroll on the images for one one style, if you select another style that index stays the same. So, for example, if selected style A for product 1 is active and I scroll all the way to the right, then click selected style B for product 1, then the image scroll we're currently on is still all the way to the right (rather than being reset)

https://github.com/ChronosTrade/FEC/blob/089dd8ca72e2bcbd79c360a8e2fff992a6a0609b/client/src/components/overview/overview_components/ImageScroll.jsx#L27-L56

**Comment by TarynCovert** [comment]
@rkmiller131  - Hey, thank you for the code review!! I do want to check though, am I misunderstanding the BRD statement below?

Overview, Default View 3rd paragraph:
"When switching between styles, the index of the image currently selected should be maintained when the gallery updates for the new style."

**Comment by rkmiller131** [comment]
Hm 🤔 yeah I could see how that is interpreted to be the functionality that you currently have. I don't know! I guess I just assumed it would reset to the top, so meh. Carry on.

**Comment by TarynCovert** [comment]
Perfect, sounds good!
